
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Oct 02 21:24:48 PDT 2022
//----------------------------------------------------

package Viper;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 7;
  public static final int LT = 16;
  public static final int ELSE = 20;
  public static final int NEG = 18;
  public static final int PLUS = 3;
  public static final int INT = 21;
  public static final int RBRACE = 11;
  public static final int RPAREN = 9;
  public static final int WHILE = 25;
  public static final int STRI = 12;
  public static final int COMP = 15;
  public static final int SEMI = 2;
  public static final int RETURN = 26;
  public static final int BOOL_CONST = 30;
  public static final int IF = 19;
  public static final int STR_CONST = 28;
  public static final int LPAREN = 8;
  public static final int COLON = 13;
  public static final int LBRACE = 10;
  public static final int ID = 31;
  public static final int LE = 17;
  public static final int INT_CONST = 29;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int DEF = 24;
  public static final int DIV = 6;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int STR = 23;
  public static final int EQ = 14;
  public static final int BOOL = 22;
  public static final int VOID = 27;
}

